### PR TITLE
Add `!joke random` command

### PR DESCRIPTION
**Pull request by bwallberg**

### CODE REVIEW

**Comment by finafisken** [comment]
jokes are bad...

**Comment by finafisken** [comment]
`invalid type: integer 200, expected a string at line 1 column 113`

**Comment by bwallberg** [comment]
Now it works 👍

**Comment by finafisken** [comment]
Add docs to README for command and we can merge

**Comment by bwallberg** [comment]
@finafisken done

**Review by finafisken — APPROVED** [review]

**Pull request merged**
